// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockcontroller

import (
	"context"

	"github.com/alexandremahdhaoui/forge-ai/pkg/generated/trackerclient"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEdgeManager creates a new instance of MockEdgeManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEdgeManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEdgeManager {
	mock := &MockEdgeManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEdgeManager is an autogenerated mock type for the EdgeManager type
type MockEdgeManager struct {
	mock.Mock
}

type MockEdgeManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEdgeManager) EXPECT() *MockEdgeManager_Expecter {
	return &MockEdgeManager_Expecter{mock: &_m.Mock}
}

// AddEdge provides a mock function for the type MockEdgeManager
func (_mock *MockEdgeManager) AddEdge(ctx context.Context, ts string, req trackerclient.EdgeRequest) (trackerclient.Edge, error) {
	ret := _mock.Called(ctx, ts, req)

	if len(ret) == 0 {
		panic("no return value specified for AddEdge")
	}

	var r0 trackerclient.Edge
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, trackerclient.EdgeRequest) (trackerclient.Edge, error)); ok {
		return returnFunc(ctx, ts, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, trackerclient.EdgeRequest) trackerclient.Edge); ok {
		r0 = returnFunc(ctx, ts, req)
	} else {
		r0 = ret.Get(0).(trackerclient.Edge)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, trackerclient.EdgeRequest) error); ok {
		r1 = returnFunc(ctx, ts, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEdgeManager_AddEdge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddEdge'
type MockEdgeManager_AddEdge_Call struct {
	*mock.Call
}

// AddEdge is a helper method to define mock.On call
//   - ctx context.Context
//   - ts string
//   - req trackerclient.EdgeRequest
func (_e *MockEdgeManager_Expecter) AddEdge(ctx interface{}, ts interface{}, req interface{}) *MockEdgeManager_AddEdge_Call {
	return &MockEdgeManager_AddEdge_Call{Call: _e.mock.On("AddEdge", ctx, ts, req)}
}

func (_c *MockEdgeManager_AddEdge_Call) Run(run func(ctx context.Context, ts string, req trackerclient.EdgeRequest)) *MockEdgeManager_AddEdge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 trackerclient.EdgeRequest
		if args[2] != nil {
			arg2 = args[2].(trackerclient.EdgeRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEdgeManager_AddEdge_Call) Return(edge trackerclient.Edge, err error) *MockEdgeManager_AddEdge_Call {
	_c.Call.Return(edge, err)
	return _c
}

func (_c *MockEdgeManager_AddEdge_Call) RunAndReturn(run func(ctx context.Context, ts string, req trackerclient.EdgeRequest) (trackerclient.Edge, error)) *MockEdgeManager_AddEdge_Call {
	_c.Call.Return(run)
	return _c
}

// ListEdges provides a mock function for the type MockEdgeManager
func (_mock *MockEdgeManager) ListEdges(ctx context.Context, ts string, params *trackerclient.ListEdgesParams) ([]trackerclient.Edge, error) {
	ret := _mock.Called(ctx, ts, params)

	if len(ret) == 0 {
		panic("no return value specified for ListEdges")
	}

	var r0 []trackerclient.Edge
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *trackerclient.ListEdgesParams) ([]trackerclient.Edge, error)); ok {
		return returnFunc(ctx, ts, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *trackerclient.ListEdgesParams) []trackerclient.Edge); ok {
		r0 = returnFunc(ctx, ts, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]trackerclient.Edge)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *trackerclient.ListEdgesParams) error); ok {
		r1 = returnFunc(ctx, ts, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEdgeManager_ListEdges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEdges'
type MockEdgeManager_ListEdges_Call struct {
	*mock.Call
}

// ListEdges is a helper method to define mock.On call
//   - ctx context.Context
//   - ts string
//   - params *trackerclient.ListEdgesParams
func (_e *MockEdgeManager_Expecter) ListEdges(ctx interface{}, ts interface{}, params interface{}) *MockEdgeManager_ListEdges_Call {
	return &MockEdgeManager_ListEdges_Call{Call: _e.mock.On("ListEdges", ctx, ts, params)}
}

func (_c *MockEdgeManager_ListEdges_Call) Run(run func(ctx context.Context, ts string, params *trackerclient.ListEdgesParams)) *MockEdgeManager_ListEdges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *trackerclient.ListEdgesParams
		if args[2] != nil {
			arg2 = args[2].(*trackerclient.ListEdgesParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEdgeManager_ListEdges_Call) Return(edges []trackerclient.Edge, err error) *MockEdgeManager_ListEdges_Call {
	_c.Call.Return(edges, err)
	return _c
}

func (_c *MockEdgeManager_ListEdges_Call) RunAndReturn(run func(ctx context.Context, ts string, params *trackerclient.ListEdgesParams) ([]trackerclient.Edge, error)) *MockEdgeManager_ListEdges_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveEdge provides a mock function for the type MockEdgeManager
func (_mock *MockEdgeManager) RemoveEdge(ctx context.Context, ts string, req trackerclient.EdgeRequest) error {
	ret := _mock.Called(ctx, ts, req)

	if len(ret) == 0 {
		panic("no return value specified for RemoveEdge")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, trackerclient.EdgeRequest) error); ok {
		r0 = returnFunc(ctx, ts, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEdgeManager_RemoveEdge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveEdge'
type MockEdgeManager_RemoveEdge_Call struct {
	*mock.Call
}

// RemoveEdge is a helper method to define mock.On call
//   - ctx context.Context
//   - ts string
//   - req trackerclient.EdgeRequest
func (_e *MockEdgeManager_Expecter) RemoveEdge(ctx interface{}, ts interface{}, req interface{}) *MockEdgeManager_RemoveEdge_Call {
	return &MockEdgeManager_RemoveEdge_Call{Call: _e.mock.On("RemoveEdge", ctx, ts, req)}
}

func (_c *MockEdgeManager_RemoveEdge_Call) Run(run func(ctx context.Context, ts string, req trackerclient.EdgeRequest)) *MockEdgeManager_RemoveEdge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 trackerclient.EdgeRequest
		if args[2] != nil {
			arg2 = args[2].(trackerclient.EdgeRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEdgeManager_RemoveEdge_Call) Return(err error) *MockEdgeManager_RemoveEdge_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEdgeManager_RemoveEdge_Call) RunAndReturn(run func(ctx context.Context, ts string, req trackerclient.EdgeRequest) error) *MockEdgeManager_RemoveEdge_Call {
	_c.Call.Return(run)
	return _c
}
