// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockcontroller

import (
	"context"

	"github.com/alexandremahdhaoui/forge-ai/internal/types"
	"github.com/alexandremahdhaoui/forge-ai/pkg/generated/trackerclient"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMemoryManager creates a new instance of MockMemoryManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMemoryManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMemoryManager {
	mock := &MockMemoryManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMemoryManager is an autogenerated mock type for the MemoryManager type
type MockMemoryManager struct {
	mock.Mock
}

type MockMemoryManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMemoryManager) EXPECT() *MockMemoryManager_Expecter {
	return &MockMemoryManager_Expecter{mock: &_m.Mock}
}

// AddComment provides a mock function for the type MockMemoryManager
func (_mock *MockMemoryManager) AddComment(ctx context.Context, ts string, ticketID string, author string, text string, tags []string) (trackerclient.Comment, error) {
	ret := _mock.Called(ctx, ts, ticketID, author, text, tags)

	if len(ret) == 0 {
		panic("no return value specified for AddComment")
	}

	var r0 trackerclient.Comment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, []string) (trackerclient.Comment, error)); ok {
		return returnFunc(ctx, ts, ticketID, author, text, tags)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, []string) trackerclient.Comment); ok {
		r0 = returnFunc(ctx, ts, ticketID, author, text, tags)
	} else {
		r0 = ret.Get(0).(trackerclient.Comment)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string, []string) error); ok {
		r1 = returnFunc(ctx, ts, ticketID, author, text, tags)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMemoryManager_AddComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddComment'
type MockMemoryManager_AddComment_Call struct {
	*mock.Call
}

// AddComment is a helper method to define mock.On call
//   - ctx context.Context
//   - ts string
//   - ticketID string
//   - author string
//   - text string
//   - tags []string
func (_e *MockMemoryManager_Expecter) AddComment(ctx interface{}, ts interface{}, ticketID interface{}, author interface{}, text interface{}, tags interface{}) *MockMemoryManager_AddComment_Call {
	return &MockMemoryManager_AddComment_Call{Call: _e.mock.On("AddComment", ctx, ts, ticketID, author, text, tags)}
}

func (_c *MockMemoryManager_AddComment_Call) Run(run func(ctx context.Context, ts string, ticketID string, author string, text string, tags []string)) *MockMemoryManager_AddComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 []string
		if args[5] != nil {
			arg5 = args[5].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockMemoryManager_AddComment_Call) Return(comment trackerclient.Comment, err error) *MockMemoryManager_AddComment_Call {
	_c.Call.Return(comment, err)
	return _c
}

func (_c *MockMemoryManager_AddComment_Call) RunAndReturn(run func(ctx context.Context, ts string, ticketID string, author string, text string, tags []string) (trackerclient.Comment, error)) *MockMemoryManager_AddComment_Call {
	_c.Call.Return(run)
	return _c
}

// ListMemories provides a mock function for the type MockMemoryManager
func (_mock *MockMemoryManager) ListMemories(ctx context.Context, ts string, ticketID string, agentID string) ([]types.Memory, error) {
	ret := _mock.Called(ctx, ts, ticketID, agentID)

	if len(ret) == 0 {
		panic("no return value specified for ListMemories")
	}

	var r0 []types.Memory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) ([]types.Memory, error)); ok {
		return returnFunc(ctx, ts, ticketID, agentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) []types.Memory); ok {
		r0 = returnFunc(ctx, ts, ticketID, agentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Memory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, ts, ticketID, agentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMemoryManager_ListMemories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMemories'
type MockMemoryManager_ListMemories_Call struct {
	*mock.Call
}

// ListMemories is a helper method to define mock.On call
//   - ctx context.Context
//   - ts string
//   - ticketID string
//   - agentID string
func (_e *MockMemoryManager_Expecter) ListMemories(ctx interface{}, ts interface{}, ticketID interface{}, agentID interface{}) *MockMemoryManager_ListMemories_Call {
	return &MockMemoryManager_ListMemories_Call{Call: _e.mock.On("ListMemories", ctx, ts, ticketID, agentID)}
}

func (_c *MockMemoryManager_ListMemories_Call) Run(run func(ctx context.Context, ts string, ticketID string, agentID string)) *MockMemoryManager_ListMemories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMemoryManager_ListMemories_Call) Return(memorys []types.Memory, err error) *MockMemoryManager_ListMemories_Call {
	_c.Call.Return(memorys, err)
	return _c
}

func (_c *MockMemoryManager_ListMemories_Call) RunAndReturn(run func(ctx context.Context, ts string, ticketID string, agentID string) ([]types.Memory, error)) *MockMemoryManager_ListMemories_Call {
	_c.Call.Return(run)
	return _c
}
