// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockcontroller

import (
	"context"

	"github.com/alexandremahdhaoui/forge-ai/internal/adapter"
	"github.com/alexandremahdhaoui/forge-ai/pkg/generated/trackerclient"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPlanManager creates a new instance of MockPlanManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlanManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPlanManager {
	mock := &MockPlanManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPlanManager is an autogenerated mock type for the PlanManager type
type MockPlanManager struct {
	mock.Mock
}

type MockPlanManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlanManager) EXPECT() *MockPlanManager_Expecter {
	return &MockPlanManager_Expecter{mock: &_m.Mock}
}

// AssignTask provides a mock function for the type MockPlanManager
func (_mock *MockPlanManager) AssignTask(ctx context.Context, ts string, ticketID string, agentID string) (trackerclient.Ticket, error) {
	ret := _mock.Called(ctx, ts, ticketID, agentID)

	if len(ret) == 0 {
		panic("no return value specified for AssignTask")
	}

	var r0 trackerclient.Ticket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (trackerclient.Ticket, error)); ok {
		return returnFunc(ctx, ts, ticketID, agentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) trackerclient.Ticket); ok {
		r0 = returnFunc(ctx, ts, ticketID, agentID)
	} else {
		r0 = ret.Get(0).(trackerclient.Ticket)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, ts, ticketID, agentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlanManager_AssignTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignTask'
type MockPlanManager_AssignTask_Call struct {
	*mock.Call
}

// AssignTask is a helper method to define mock.On call
//   - ctx context.Context
//   - ts string
//   - ticketID string
//   - agentID string
func (_e *MockPlanManager_Expecter) AssignTask(ctx interface{}, ts interface{}, ticketID interface{}, agentID interface{}) *MockPlanManager_AssignTask_Call {
	return &MockPlanManager_AssignTask_Call{Call: _e.mock.On("AssignTask", ctx, ts, ticketID, agentID)}
}

func (_c *MockPlanManager_AssignTask_Call) Run(run func(ctx context.Context, ts string, ticketID string, agentID string)) *MockPlanManager_AssignTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPlanManager_AssignTask_Call) Return(ticket trackerclient.Ticket, err error) *MockPlanManager_AssignTask_Call {
	_c.Call.Return(ticket, err)
	return _c
}

func (_c *MockPlanManager_AssignTask_Call) RunAndReturn(run func(ctx context.Context, ts string, ticketID string, agentID string) (trackerclient.Ticket, error)) *MockPlanManager_AssignTask_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteTask provides a mock function for the type MockPlanManager
func (_mock *MockPlanManager) CompleteTask(ctx context.Context, ts string, ticketID string) (trackerclient.Ticket, error) {
	ret := _mock.Called(ctx, ts, ticketID)

	if len(ret) == 0 {
		panic("no return value specified for CompleteTask")
	}

	var r0 trackerclient.Ticket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (trackerclient.Ticket, error)); ok {
		return returnFunc(ctx, ts, ticketID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) trackerclient.Ticket); ok {
		r0 = returnFunc(ctx, ts, ticketID)
	} else {
		r0 = ret.Get(0).(trackerclient.Ticket)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, ts, ticketID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlanManager_CompleteTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteTask'
type MockPlanManager_CompleteTask_Call struct {
	*mock.Call
}

// CompleteTask is a helper method to define mock.On call
//   - ctx context.Context
//   - ts string
//   - ticketID string
func (_e *MockPlanManager_Expecter) CompleteTask(ctx interface{}, ts interface{}, ticketID interface{}) *MockPlanManager_CompleteTask_Call {
	return &MockPlanManager_CompleteTask_Call{Call: _e.mock.On("CompleteTask", ctx, ts, ticketID)}
}

func (_c *MockPlanManager_CompleteTask_Call) Run(run func(ctx context.Context, ts string, ticketID string)) *MockPlanManager_CompleteTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPlanManager_CompleteTask_Call) Return(ticket trackerclient.Ticket, err error) *MockPlanManager_CompleteTask_Call {
	_c.Call.Return(ticket, err)
	return _c
}

func (_c *MockPlanManager_CompleteTask_Call) RunAndReturn(run func(ctx context.Context, ts string, ticketID string) (trackerclient.Ticket, error)) *MockPlanManager_CompleteTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetaPlan provides a mock function for the type MockPlanManager
func (_mock *MockPlanManager) GetMetaPlan(ctx context.Context, ts string, id string) (trackerclient.MetaPlan, error) {
	ret := _mock.Called(ctx, ts, id)

	if len(ret) == 0 {
		panic("no return value specified for GetMetaPlan")
	}

	var r0 trackerclient.MetaPlan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (trackerclient.MetaPlan, error)); ok {
		return returnFunc(ctx, ts, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) trackerclient.MetaPlan); ok {
		r0 = returnFunc(ctx, ts, id)
	} else {
		r0 = ret.Get(0).(trackerclient.MetaPlan)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, ts, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlanManager_GetMetaPlan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetaPlan'
type MockPlanManager_GetMetaPlan_Call struct {
	*mock.Call
}

// GetMetaPlan is a helper method to define mock.On call
//   - ctx context.Context
//   - ts string
//   - id string
func (_e *MockPlanManager_Expecter) GetMetaPlan(ctx interface{}, ts interface{}, id interface{}) *MockPlanManager_GetMetaPlan_Call {
	return &MockPlanManager_GetMetaPlan_Call{Call: _e.mock.On("GetMetaPlan", ctx, ts, id)}
}

func (_c *MockPlanManager_GetMetaPlan_Call) Run(run func(ctx context.Context, ts string, id string)) *MockPlanManager_GetMetaPlan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPlanManager_GetMetaPlan_Call) Return(metaPlan trackerclient.MetaPlan, err error) *MockPlanManager_GetMetaPlan_Call {
	_c.Call.Return(metaPlan, err)
	return _c
}

func (_c *MockPlanManager_GetMetaPlan_Call) RunAndReturn(run func(ctx context.Context, ts string, id string) (trackerclient.MetaPlan, error)) *MockPlanManager_GetMetaPlan_Call {
	_c.Call.Return(run)
	return _c
}

// GetPlanState provides a mock function for the type MockPlanManager
func (_mock *MockPlanManager) GetPlanState(ctx context.Context, ts string, id string) (trackerclient.Plan, error) {
	ret := _mock.Called(ctx, ts, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPlanState")
	}

	var r0 trackerclient.Plan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (trackerclient.Plan, error)); ok {
		return returnFunc(ctx, ts, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) trackerclient.Plan); ok {
		r0 = returnFunc(ctx, ts, id)
	} else {
		r0 = ret.Get(0).(trackerclient.Plan)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, ts, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlanManager_GetPlanState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlanState'
type MockPlanManager_GetPlanState_Call struct {
	*mock.Call
}

// GetPlanState is a helper method to define mock.On call
//   - ctx context.Context
//   - ts string
//   - id string
func (_e *MockPlanManager_Expecter) GetPlanState(ctx interface{}, ts interface{}, id interface{}) *MockPlanManager_GetPlanState_Call {
	return &MockPlanManager_GetPlanState_Call{Call: _e.mock.On("GetPlanState", ctx, ts, id)}
}

func (_c *MockPlanManager_GetPlanState_Call) Run(run func(ctx context.Context, ts string, id string)) *MockPlanManager_GetPlanState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPlanManager_GetPlanState_Call) Return(plan trackerclient.Plan, err error) *MockPlanManager_GetPlanState_Call {
	_c.Call.Return(plan, err)
	return _c
}

func (_c *MockPlanManager_GetPlanState_Call) RunAndReturn(run func(ctx context.Context, ts string, id string) (trackerclient.Plan, error)) *MockPlanManager_GetPlanState_Call {
	_c.Call.Return(run)
	return _c
}

// GetTask provides a mock function for the type MockPlanManager
func (_mock *MockPlanManager) GetTask(ctx context.Context, ts string, id string) (trackerclient.Ticket, error) {
	ret := _mock.Called(ctx, ts, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTask")
	}

	var r0 trackerclient.Ticket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (trackerclient.Ticket, error)); ok {
		return returnFunc(ctx, ts, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) trackerclient.Ticket); ok {
		r0 = returnFunc(ctx, ts, id)
	} else {
		r0 = ret.Get(0).(trackerclient.Ticket)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, ts, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlanManager_GetTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTask'
type MockPlanManager_GetTask_Call struct {
	*mock.Call
}

// GetTask is a helper method to define mock.On call
//   - ctx context.Context
//   - ts string
//   - id string
func (_e *MockPlanManager_Expecter) GetTask(ctx interface{}, ts interface{}, id interface{}) *MockPlanManager_GetTask_Call {
	return &MockPlanManager_GetTask_Call{Call: _e.mock.On("GetTask", ctx, ts, id)}
}

func (_c *MockPlanManager_GetTask_Call) Run(run func(ctx context.Context, ts string, id string)) *MockPlanManager_GetTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPlanManager_GetTask_Call) Return(ticket trackerclient.Ticket, err error) *MockPlanManager_GetTask_Call {
	_c.Call.Return(ticket, err)
	return _c
}

func (_c *MockPlanManager_GetTask_Call) RunAndReturn(run func(ctx context.Context, ts string, id string) (trackerclient.Ticket, error)) *MockPlanManager_GetTask_Call {
	_c.Call.Return(run)
	return _c
}

// ListMetaPlans provides a mock function for the type MockPlanManager
func (_mock *MockPlanManager) ListMetaPlans(ctx context.Context, ts string) ([]trackerclient.MetaPlan, error) {
	ret := _mock.Called(ctx, ts)

	if len(ret) == 0 {
		panic("no return value specified for ListMetaPlans")
	}

	var r0 []trackerclient.MetaPlan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]trackerclient.MetaPlan, error)); ok {
		return returnFunc(ctx, ts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []trackerclient.MetaPlan); ok {
		r0 = returnFunc(ctx, ts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]trackerclient.MetaPlan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlanManager_ListMetaPlans_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMetaPlans'
type MockPlanManager_ListMetaPlans_Call struct {
	*mock.Call
}

// ListMetaPlans is a helper method to define mock.On call
//   - ctx context.Context
//   - ts string
func (_e *MockPlanManager_Expecter) ListMetaPlans(ctx interface{}, ts interface{}) *MockPlanManager_ListMetaPlans_Call {
	return &MockPlanManager_ListMetaPlans_Call{Call: _e.mock.On("ListMetaPlans", ctx, ts)}
}

func (_c *MockPlanManager_ListMetaPlans_Call) Run(run func(ctx context.Context, ts string)) *MockPlanManager_ListMetaPlans_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlanManager_ListMetaPlans_Call) Return(metaPlans []trackerclient.MetaPlan, err error) *MockPlanManager_ListMetaPlans_Call {
	_c.Call.Return(metaPlans, err)
	return _c
}

func (_c *MockPlanManager_ListMetaPlans_Call) RunAndReturn(run func(ctx context.Context, ts string) ([]trackerclient.MetaPlan, error)) *MockPlanManager_ListMetaPlans_Call {
	_c.Call.Return(run)
	return _c
}

// ListPlans provides a mock function for the type MockPlanManager
func (_mock *MockPlanManager) ListPlans(ctx context.Context, ts string) ([]trackerclient.Plan, error) {
	ret := _mock.Called(ctx, ts)

	if len(ret) == 0 {
		panic("no return value specified for ListPlans")
	}

	var r0 []trackerclient.Plan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]trackerclient.Plan, error)); ok {
		return returnFunc(ctx, ts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []trackerclient.Plan); ok {
		r0 = returnFunc(ctx, ts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]trackerclient.Plan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlanManager_ListPlans_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPlans'
type MockPlanManager_ListPlans_Call struct {
	*mock.Call
}

// ListPlans is a helper method to define mock.On call
//   - ctx context.Context
//   - ts string
func (_e *MockPlanManager_Expecter) ListPlans(ctx interface{}, ts interface{}) *MockPlanManager_ListPlans_Call {
	return &MockPlanManager_ListPlans_Call{Call: _e.mock.On("ListPlans", ctx, ts)}
}

func (_c *MockPlanManager_ListPlans_Call) Run(run func(ctx context.Context, ts string)) *MockPlanManager_ListPlans_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlanManager_ListPlans_Call) Return(plans []trackerclient.Plan, err error) *MockPlanManager_ListPlans_Call {
	_c.Call.Return(plans, err)
	return _c
}

func (_c *MockPlanManager_ListPlans_Call) RunAndReturn(run func(ctx context.Context, ts string) ([]trackerclient.Plan, error)) *MockPlanManager_ListPlans_Call {
	_c.Call.Return(run)
	return _c
}

// ListTasks provides a mock function for the type MockPlanManager
func (_mock *MockPlanManager) ListTasks(ctx context.Context, ts string, filter adapter.TicketFilter) ([]trackerclient.Ticket, error) {
	ret := _mock.Called(ctx, ts, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListTasks")
	}

	var r0 []trackerclient.Ticket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, adapter.TicketFilter) ([]trackerclient.Ticket, error)); ok {
		return returnFunc(ctx, ts, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, adapter.TicketFilter) []trackerclient.Ticket); ok {
		r0 = returnFunc(ctx, ts, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]trackerclient.Ticket)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, adapter.TicketFilter) error); ok {
		r1 = returnFunc(ctx, ts, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlanManager_ListTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTasks'
type MockPlanManager_ListTasks_Call struct {
	*mock.Call
}

// ListTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - ts string
//   - filter adapter.TicketFilter
func (_e *MockPlanManager_Expecter) ListTasks(ctx interface{}, ts interface{}, filter interface{}) *MockPlanManager_ListTasks_Call {
	return &MockPlanManager_ListTasks_Call{Call: _e.mock.On("ListTasks", ctx, ts, filter)}
}

func (_c *MockPlanManager_ListTasks_Call) Run(run func(ctx context.Context, ts string, filter adapter.TicketFilter)) *MockPlanManager_ListTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 adapter.TicketFilter
		if args[2] != nil {
			arg2 = args[2].(adapter.TicketFilter)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPlanManager_ListTasks_Call) Return(tickets []trackerclient.Ticket, err error) *MockPlanManager_ListTasks_Call {
	_c.Call.Return(tickets, err)
	return _c
}

func (_c *MockPlanManager_ListTasks_Call) RunAndReturn(run func(ctx context.Context, ts string, filter adapter.TicketFilter) ([]trackerclient.Ticket, error)) *MockPlanManager_ListTasks_Call {
	_c.Call.Return(run)
	return _c
}
