// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockcontroller

import (
	"context"

	"github.com/alexandremahdhaoui/forge-ai/pkg/generated/trackerclient"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTrackingSetManager creates a new instance of MockTrackingSetManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTrackingSetManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTrackingSetManager {
	mock := &MockTrackingSetManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTrackingSetManager is an autogenerated mock type for the TrackingSetManager type
type MockTrackingSetManager struct {
	mock.Mock
}

type MockTrackingSetManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTrackingSetManager) EXPECT() *MockTrackingSetManager_Expecter {
	return &MockTrackingSetManager_Expecter{mock: &_m.Mock}
}

// CreateTrackingSet provides a mock function for the type MockTrackingSetManager
func (_mock *MockTrackingSetManager) CreateTrackingSet(ctx context.Context, name string) (trackerclient.TrackingSet, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for CreateTrackingSet")
	}

	var r0 trackerclient.TrackingSet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (trackerclient.TrackingSet, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) trackerclient.TrackingSet); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(trackerclient.TrackingSet)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTrackingSetManager_CreateTrackingSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTrackingSet'
type MockTrackingSetManager_CreateTrackingSet_Call struct {
	*mock.Call
}

// CreateTrackingSet is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockTrackingSetManager_Expecter) CreateTrackingSet(ctx interface{}, name interface{}) *MockTrackingSetManager_CreateTrackingSet_Call {
	return &MockTrackingSetManager_CreateTrackingSet_Call{Call: _e.mock.On("CreateTrackingSet", ctx, name)}
}

func (_c *MockTrackingSetManager_CreateTrackingSet_Call) Run(run func(ctx context.Context, name string)) *MockTrackingSetManager_CreateTrackingSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTrackingSetManager_CreateTrackingSet_Call) Return(trackingSet trackerclient.TrackingSet, err error) *MockTrackingSetManager_CreateTrackingSet_Call {
	_c.Call.Return(trackingSet, err)
	return _c
}

func (_c *MockTrackingSetManager_CreateTrackingSet_Call) RunAndReturn(run func(ctx context.Context, name string) (trackerclient.TrackingSet, error)) *MockTrackingSetManager_CreateTrackingSet_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTrackingSet provides a mock function for the type MockTrackingSetManager
func (_mock *MockTrackingSetManager) DeleteTrackingSet(ctx context.Context, ts string) error {
	ret := _mock.Called(ctx, ts)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTrackingSet")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, ts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTrackingSetManager_DeleteTrackingSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTrackingSet'
type MockTrackingSetManager_DeleteTrackingSet_Call struct {
	*mock.Call
}

// DeleteTrackingSet is a helper method to define mock.On call
//   - ctx context.Context
//   - ts string
func (_e *MockTrackingSetManager_Expecter) DeleteTrackingSet(ctx interface{}, ts interface{}) *MockTrackingSetManager_DeleteTrackingSet_Call {
	return &MockTrackingSetManager_DeleteTrackingSet_Call{Call: _e.mock.On("DeleteTrackingSet", ctx, ts)}
}

func (_c *MockTrackingSetManager_DeleteTrackingSet_Call) Run(run func(ctx context.Context, ts string)) *MockTrackingSetManager_DeleteTrackingSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTrackingSetManager_DeleteTrackingSet_Call) Return(err error) *MockTrackingSetManager_DeleteTrackingSet_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTrackingSetManager_DeleteTrackingSet_Call) RunAndReturn(run func(ctx context.Context, ts string) error) *MockTrackingSetManager_DeleteTrackingSet_Call {
	_c.Call.Return(run)
	return _c
}

// GetTrackingSet provides a mock function for the type MockTrackingSetManager
func (_mock *MockTrackingSetManager) GetTrackingSet(ctx context.Context, ts string) (trackerclient.TrackingSet, error) {
	ret := _mock.Called(ctx, ts)

	if len(ret) == 0 {
		panic("no return value specified for GetTrackingSet")
	}

	var r0 trackerclient.TrackingSet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (trackerclient.TrackingSet, error)); ok {
		return returnFunc(ctx, ts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) trackerclient.TrackingSet); ok {
		r0 = returnFunc(ctx, ts)
	} else {
		r0 = ret.Get(0).(trackerclient.TrackingSet)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTrackingSetManager_GetTrackingSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTrackingSet'
type MockTrackingSetManager_GetTrackingSet_Call struct {
	*mock.Call
}

// GetTrackingSet is a helper method to define mock.On call
//   - ctx context.Context
//   - ts string
func (_e *MockTrackingSetManager_Expecter) GetTrackingSet(ctx interface{}, ts interface{}) *MockTrackingSetManager_GetTrackingSet_Call {
	return &MockTrackingSetManager_GetTrackingSet_Call{Call: _e.mock.On("GetTrackingSet", ctx, ts)}
}

func (_c *MockTrackingSetManager_GetTrackingSet_Call) Run(run func(ctx context.Context, ts string)) *MockTrackingSetManager_GetTrackingSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTrackingSetManager_GetTrackingSet_Call) Return(trackingSet trackerclient.TrackingSet, err error) *MockTrackingSetManager_GetTrackingSet_Call {
	_c.Call.Return(trackingSet, err)
	return _c
}

func (_c *MockTrackingSetManager_GetTrackingSet_Call) RunAndReturn(run func(ctx context.Context, ts string) (trackerclient.TrackingSet, error)) *MockTrackingSetManager_GetTrackingSet_Call {
	_c.Call.Return(run)
	return _c
}

// ListTrackingSets provides a mock function for the type MockTrackingSetManager
func (_mock *MockTrackingSetManager) ListTrackingSets(ctx context.Context) ([]trackerclient.TrackingSet, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTrackingSets")
	}

	var r0 []trackerclient.TrackingSet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]trackerclient.TrackingSet, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []trackerclient.TrackingSet); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]trackerclient.TrackingSet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTrackingSetManager_ListTrackingSets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTrackingSets'
type MockTrackingSetManager_ListTrackingSets_Call struct {
	*mock.Call
}

// ListTrackingSets is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTrackingSetManager_Expecter) ListTrackingSets(ctx interface{}) *MockTrackingSetManager_ListTrackingSets_Call {
	return &MockTrackingSetManager_ListTrackingSets_Call{Call: _e.mock.On("ListTrackingSets", ctx)}
}

func (_c *MockTrackingSetManager_ListTrackingSets_Call) Run(run func(ctx context.Context)) *MockTrackingSetManager_ListTrackingSets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTrackingSetManager_ListTrackingSets_Call) Return(trackingSets []trackerclient.TrackingSet, err error) *MockTrackingSetManager_ListTrackingSets_Call {
	_c.Call.Return(trackingSets, err)
	return _c
}

func (_c *MockTrackingSetManager_ListTrackingSets_Call) RunAndReturn(run func(ctx context.Context) ([]trackerclient.TrackingSet, error)) *MockTrackingSetManager_ListTrackingSets_Call {
	_c.Call.Return(run)
	return _c
}
