// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockadapter

import (
	"context"

	"github.com/alexandremahdhaoui/forge-ai/internal/adapter"
	"github.com/alexandremahdhaoui/forge-ai/pkg/generated/trackerclient"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTrackerClient creates a new instance of MockTrackerClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTrackerClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTrackerClient {
	mock := &MockTrackerClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTrackerClient is an autogenerated mock type for the TrackerClient type
type MockTrackerClient struct {
	mock.Mock
}

type MockTrackerClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTrackerClient) EXPECT() *MockTrackerClient_Expecter {
	return &MockTrackerClient_Expecter{mock: &_m.Mock}
}

// AddComment provides a mock function for the type MockTrackerClient
func (_mock *MockTrackerClient) AddComment(ctx context.Context, ts string, ticketID string, req trackerclient.AddCommentRequest) (trackerclient.Comment, error) {
	ret := _mock.Called(ctx, ts, ticketID, req)

	if len(ret) == 0 {
		panic("no return value specified for AddComment")
	}

	var r0 trackerclient.Comment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, trackerclient.AddCommentRequest) (trackerclient.Comment, error)); ok {
		return returnFunc(ctx, ts, ticketID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, trackerclient.AddCommentRequest) trackerclient.Comment); ok {
		r0 = returnFunc(ctx, ts, ticketID, req)
	} else {
		r0 = ret.Get(0).(trackerclient.Comment)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, trackerclient.AddCommentRequest) error); ok {
		r1 = returnFunc(ctx, ts, ticketID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTrackerClient_AddComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddComment'
type MockTrackerClient_AddComment_Call struct {
	*mock.Call
}

// AddComment is a helper method to define mock.On call
//   - ctx context.Context
//   - ts string
//   - ticketID string
//   - req trackerclient.AddCommentRequest
func (_e *MockTrackerClient_Expecter) AddComment(ctx interface{}, ts interface{}, ticketID interface{}, req interface{}) *MockTrackerClient_AddComment_Call {
	return &MockTrackerClient_AddComment_Call{Call: _e.mock.On("AddComment", ctx, ts, ticketID, req)}
}

func (_c *MockTrackerClient_AddComment_Call) Run(run func(ctx context.Context, ts string, ticketID string, req trackerclient.AddCommentRequest)) *MockTrackerClient_AddComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 trackerclient.AddCommentRequest
		if args[3] != nil {
			arg3 = args[3].(trackerclient.AddCommentRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTrackerClient_AddComment_Call) Return(comment trackerclient.Comment, err error) *MockTrackerClient_AddComment_Call {
	_c.Call.Return(comment, err)
	return _c
}

func (_c *MockTrackerClient_AddComment_Call) RunAndReturn(run func(ctx context.Context, ts string, ticketID string, req trackerclient.AddCommentRequest) (trackerclient.Comment, error)) *MockTrackerClient_AddComment_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlocking provides a mock function for the type MockTrackerClient
func (_mock *MockTrackerClient) GetBlocking(ctx context.Context, ts string, ticketID string) ([]trackerclient.Ticket, error) {
	ret := _mock.Called(ctx, ts, ticketID)

	if len(ret) == 0 {
		panic("no return value specified for GetBlocking")
	}

	var r0 []trackerclient.Ticket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]trackerclient.Ticket, error)); ok {
		return returnFunc(ctx, ts, ticketID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []trackerclient.Ticket); ok {
		r0 = returnFunc(ctx, ts, ticketID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]trackerclient.Ticket)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, ts, ticketID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTrackerClient_GetBlocking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlocking'
type MockTrackerClient_GetBlocking_Call struct {
	*mock.Call
}

// GetBlocking is a helper method to define mock.On call
//   - ctx context.Context
//   - ts string
//   - ticketID string
func (_e *MockTrackerClient_Expecter) GetBlocking(ctx interface{}, ts interface{}, ticketID interface{}) *MockTrackerClient_GetBlocking_Call {
	return &MockTrackerClient_GetBlocking_Call{Call: _e.mock.On("GetBlocking", ctx, ts, ticketID)}
}

func (_c *MockTrackerClient_GetBlocking_Call) Run(run func(ctx context.Context, ts string, ticketID string)) *MockTrackerClient_GetBlocking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTrackerClient_GetBlocking_Call) Return(tickets []trackerclient.Ticket, err error) *MockTrackerClient_GetBlocking_Call {
	_c.Call.Return(tickets, err)
	return _c
}

func (_c *MockTrackerClient_GetBlocking_Call) RunAndReturn(run func(ctx context.Context, ts string, ticketID string) ([]trackerclient.Ticket, error)) *MockTrackerClient_GetBlocking_Call {
	_c.Call.Return(run)
	return _c
}

// GetChildren provides a mock function for the type MockTrackerClient
func (_mock *MockTrackerClient) GetChildren(ctx context.Context, ts string, ticketID string) ([]trackerclient.Ticket, error) {
	ret := _mock.Called(ctx, ts, ticketID)

	if len(ret) == 0 {
		panic("no return value specified for GetChildren")
	}

	var r0 []trackerclient.Ticket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]trackerclient.Ticket, error)); ok {
		return returnFunc(ctx, ts, ticketID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []trackerclient.Ticket); ok {
		r0 = returnFunc(ctx, ts, ticketID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]trackerclient.Ticket)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, ts, ticketID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTrackerClient_GetChildren_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChildren'
type MockTrackerClient_GetChildren_Call struct {
	*mock.Call
}

// GetChildren is a helper method to define mock.On call
//   - ctx context.Context
//   - ts string
//   - ticketID string
func (_e *MockTrackerClient_Expecter) GetChildren(ctx interface{}, ts interface{}, ticketID interface{}) *MockTrackerClient_GetChildren_Call {
	return &MockTrackerClient_GetChildren_Call{Call: _e.mock.On("GetChildren", ctx, ts, ticketID)}
}

func (_c *MockTrackerClient_GetChildren_Call) Run(run func(ctx context.Context, ts string, ticketID string)) *MockTrackerClient_GetChildren_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTrackerClient_GetChildren_Call) Return(tickets []trackerclient.Ticket, err error) *MockTrackerClient_GetChildren_Call {
	_c.Call.Return(tickets, err)
	return _c
}

func (_c *MockTrackerClient_GetChildren_Call) RunAndReturn(run func(ctx context.Context, ts string, ticketID string) ([]trackerclient.Ticket, error)) *MockTrackerClient_GetChildren_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetaPlan provides a mock function for the type MockTrackerClient
func (_mock *MockTrackerClient) GetMetaPlan(ctx context.Context, ts string, id string) (trackerclient.MetaPlan, error) {
	ret := _mock.Called(ctx, ts, id)

	if len(ret) == 0 {
		panic("no return value specified for GetMetaPlan")
	}

	var r0 trackerclient.MetaPlan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (trackerclient.MetaPlan, error)); ok {
		return returnFunc(ctx, ts, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) trackerclient.MetaPlan); ok {
		r0 = returnFunc(ctx, ts, id)
	} else {
		r0 = ret.Get(0).(trackerclient.MetaPlan)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, ts, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTrackerClient_GetMetaPlan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetaPlan'
type MockTrackerClient_GetMetaPlan_Call struct {
	*mock.Call
}

// GetMetaPlan is a helper method to define mock.On call
//   - ctx context.Context
//   - ts string
//   - id string
func (_e *MockTrackerClient_Expecter) GetMetaPlan(ctx interface{}, ts interface{}, id interface{}) *MockTrackerClient_GetMetaPlan_Call {
	return &MockTrackerClient_GetMetaPlan_Call{Call: _e.mock.On("GetMetaPlan", ctx, ts, id)}
}

func (_c *MockTrackerClient_GetMetaPlan_Call) Run(run func(ctx context.Context, ts string, id string)) *MockTrackerClient_GetMetaPlan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTrackerClient_GetMetaPlan_Call) Return(metaPlan trackerclient.MetaPlan, err error) *MockTrackerClient_GetMetaPlan_Call {
	_c.Call.Return(metaPlan, err)
	return _c
}

func (_c *MockTrackerClient_GetMetaPlan_Call) RunAndReturn(run func(ctx context.Context, ts string, id string) (trackerclient.MetaPlan, error)) *MockTrackerClient_GetMetaPlan_Call {
	_c.Call.Return(run)
	return _c
}

// GetPlan provides a mock function for the type MockTrackerClient
func (_mock *MockTrackerClient) GetPlan(ctx context.Context, ts string, id string) (trackerclient.Plan, error) {
	ret := _mock.Called(ctx, ts, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPlan")
	}

	var r0 trackerclient.Plan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (trackerclient.Plan, error)); ok {
		return returnFunc(ctx, ts, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) trackerclient.Plan); ok {
		r0 = returnFunc(ctx, ts, id)
	} else {
		r0 = ret.Get(0).(trackerclient.Plan)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, ts, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTrackerClient_GetPlan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlan'
type MockTrackerClient_GetPlan_Call struct {
	*mock.Call
}

// GetPlan is a helper method to define mock.On call
//   - ctx context.Context
//   - ts string
//   - id string
func (_e *MockTrackerClient_Expecter) GetPlan(ctx interface{}, ts interface{}, id interface{}) *MockTrackerClient_GetPlan_Call {
	return &MockTrackerClient_GetPlan_Call{Call: _e.mock.On("GetPlan", ctx, ts, id)}
}

func (_c *MockTrackerClient_GetPlan_Call) Run(run func(ctx context.Context, ts string, id string)) *MockTrackerClient_GetPlan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTrackerClient_GetPlan_Call) Return(plan trackerclient.Plan, err error) *MockTrackerClient_GetPlan_Call {
	_c.Call.Return(plan, err)
	return _c
}

func (_c *MockTrackerClient_GetPlan_Call) RunAndReturn(run func(ctx context.Context, ts string, id string) (trackerclient.Plan, error)) *MockTrackerClient_GetPlan_Call {
	_c.Call.Return(run)
	return _c
}

// GetTicket provides a mock function for the type MockTrackerClient
func (_mock *MockTrackerClient) GetTicket(ctx context.Context, ts string, id string) (trackerclient.Ticket, error) {
	ret := _mock.Called(ctx, ts, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTicket")
	}

	var r0 trackerclient.Ticket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (trackerclient.Ticket, error)); ok {
		return returnFunc(ctx, ts, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) trackerclient.Ticket); ok {
		r0 = returnFunc(ctx, ts, id)
	} else {
		r0 = ret.Get(0).(trackerclient.Ticket)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, ts, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTrackerClient_GetTicket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTicket'
type MockTrackerClient_GetTicket_Call struct {
	*mock.Call
}

// GetTicket is a helper method to define mock.On call
//   - ctx context.Context
//   - ts string
//   - id string
func (_e *MockTrackerClient_Expecter) GetTicket(ctx interface{}, ts interface{}, id interface{}) *MockTrackerClient_GetTicket_Call {
	return &MockTrackerClient_GetTicket_Call{Call: _e.mock.On("GetTicket", ctx, ts, id)}
}

func (_c *MockTrackerClient_GetTicket_Call) Run(run func(ctx context.Context, ts string, id string)) *MockTrackerClient_GetTicket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTrackerClient_GetTicket_Call) Return(ticket trackerclient.Ticket, err error) *MockTrackerClient_GetTicket_Call {
	_c.Call.Return(ticket, err)
	return _c
}

func (_c *MockTrackerClient_GetTicket_Call) RunAndReturn(run func(ctx context.Context, ts string, id string) (trackerclient.Ticket, error)) *MockTrackerClient_GetTicket_Call {
	_c.Call.Return(run)
	return _c
}

// ListMetaPlans provides a mock function for the type MockTrackerClient
func (_mock *MockTrackerClient) ListMetaPlans(ctx context.Context, ts string) ([]trackerclient.MetaPlan, error) {
	ret := _mock.Called(ctx, ts)

	if len(ret) == 0 {
		panic("no return value specified for ListMetaPlans")
	}

	var r0 []trackerclient.MetaPlan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]trackerclient.MetaPlan, error)); ok {
		return returnFunc(ctx, ts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []trackerclient.MetaPlan); ok {
		r0 = returnFunc(ctx, ts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]trackerclient.MetaPlan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTrackerClient_ListMetaPlans_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMetaPlans'
type MockTrackerClient_ListMetaPlans_Call struct {
	*mock.Call
}

// ListMetaPlans is a helper method to define mock.On call
//   - ctx context.Context
//   - ts string
func (_e *MockTrackerClient_Expecter) ListMetaPlans(ctx interface{}, ts interface{}) *MockTrackerClient_ListMetaPlans_Call {
	return &MockTrackerClient_ListMetaPlans_Call{Call: _e.mock.On("ListMetaPlans", ctx, ts)}
}

func (_c *MockTrackerClient_ListMetaPlans_Call) Run(run func(ctx context.Context, ts string)) *MockTrackerClient_ListMetaPlans_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTrackerClient_ListMetaPlans_Call) Return(metaPlans []trackerclient.MetaPlan, err error) *MockTrackerClient_ListMetaPlans_Call {
	_c.Call.Return(metaPlans, err)
	return _c
}

func (_c *MockTrackerClient_ListMetaPlans_Call) RunAndReturn(run func(ctx context.Context, ts string) ([]trackerclient.MetaPlan, error)) *MockTrackerClient_ListMetaPlans_Call {
	_c.Call.Return(run)
	return _c
}

// ListPlans provides a mock function for the type MockTrackerClient
func (_mock *MockTrackerClient) ListPlans(ctx context.Context, ts string) ([]trackerclient.Plan, error) {
	ret := _mock.Called(ctx, ts)

	if len(ret) == 0 {
		panic("no return value specified for ListPlans")
	}

	var r0 []trackerclient.Plan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]trackerclient.Plan, error)); ok {
		return returnFunc(ctx, ts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []trackerclient.Plan); ok {
		r0 = returnFunc(ctx, ts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]trackerclient.Plan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTrackerClient_ListPlans_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPlans'
type MockTrackerClient_ListPlans_Call struct {
	*mock.Call
}

// ListPlans is a helper method to define mock.On call
//   - ctx context.Context
//   - ts string
func (_e *MockTrackerClient_Expecter) ListPlans(ctx interface{}, ts interface{}) *MockTrackerClient_ListPlans_Call {
	return &MockTrackerClient_ListPlans_Call{Call: _e.mock.On("ListPlans", ctx, ts)}
}

func (_c *MockTrackerClient_ListPlans_Call) Run(run func(ctx context.Context, ts string)) *MockTrackerClient_ListPlans_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTrackerClient_ListPlans_Call) Return(plans []trackerclient.Plan, err error) *MockTrackerClient_ListPlans_Call {
	_c.Call.Return(plans, err)
	return _c
}

func (_c *MockTrackerClient_ListPlans_Call) RunAndReturn(run func(ctx context.Context, ts string) ([]trackerclient.Plan, error)) *MockTrackerClient_ListPlans_Call {
	_c.Call.Return(run)
	return _c
}

// ListTickets provides a mock function for the type MockTrackerClient
func (_mock *MockTrackerClient) ListTickets(ctx context.Context, ts string, filter adapter.TicketFilter) ([]trackerclient.Ticket, error) {
	ret := _mock.Called(ctx, ts, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListTickets")
	}

	var r0 []trackerclient.Ticket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, adapter.TicketFilter) ([]trackerclient.Ticket, error)); ok {
		return returnFunc(ctx, ts, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, adapter.TicketFilter) []trackerclient.Ticket); ok {
		r0 = returnFunc(ctx, ts, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]trackerclient.Ticket)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, adapter.TicketFilter) error); ok {
		r1 = returnFunc(ctx, ts, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTrackerClient_ListTickets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTickets'
type MockTrackerClient_ListTickets_Call struct {
	*mock.Call
}

// ListTickets is a helper method to define mock.On call
//   - ctx context.Context
//   - ts string
//   - filter adapter.TicketFilter
func (_e *MockTrackerClient_Expecter) ListTickets(ctx interface{}, ts interface{}, filter interface{}) *MockTrackerClient_ListTickets_Call {
	return &MockTrackerClient_ListTickets_Call{Call: _e.mock.On("ListTickets", ctx, ts, filter)}
}

func (_c *MockTrackerClient_ListTickets_Call) Run(run func(ctx context.Context, ts string, filter adapter.TicketFilter)) *MockTrackerClient_ListTickets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 adapter.TicketFilter
		if args[2] != nil {
			arg2 = args[2].(adapter.TicketFilter)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTrackerClient_ListTickets_Call) Return(tickets []trackerclient.Ticket, err error) *MockTrackerClient_ListTickets_Call {
	_c.Call.Return(tickets, err)
	return _c
}

func (_c *MockTrackerClient_ListTickets_Call) RunAndReturn(run func(ctx context.Context, ts string, filter adapter.TicketFilter) ([]trackerclient.Ticket, error)) *MockTrackerClient_ListTickets_Call {
	_c.Call.Return(run)
	return _c
}

// ListTrackingSets provides a mock function for the type MockTrackerClient
func (_mock *MockTrackerClient) ListTrackingSets(ctx context.Context) ([]trackerclient.TrackingSet, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTrackingSets")
	}

	var r0 []trackerclient.TrackingSet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]trackerclient.TrackingSet, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []trackerclient.TrackingSet); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]trackerclient.TrackingSet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTrackerClient_ListTrackingSets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTrackingSets'
type MockTrackerClient_ListTrackingSets_Call struct {
	*mock.Call
}

// ListTrackingSets is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTrackerClient_Expecter) ListTrackingSets(ctx interface{}) *MockTrackerClient_ListTrackingSets_Call {
	return &MockTrackerClient_ListTrackingSets_Call{Call: _e.mock.On("ListTrackingSets", ctx)}
}

func (_c *MockTrackerClient_ListTrackingSets_Call) Run(run func(ctx context.Context)) *MockTrackerClient_ListTrackingSets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTrackerClient_ListTrackingSets_Call) Return(trackingSets []trackerclient.TrackingSet, err error) *MockTrackerClient_ListTrackingSets_Call {
	_c.Call.Return(trackingSets, err)
	return _c
}

func (_c *MockTrackerClient_ListTrackingSets_Call) RunAndReturn(run func(ctx context.Context) ([]trackerclient.TrackingSet, error)) *MockTrackerClient_ListTrackingSets_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTicket provides a mock function for the type MockTrackerClient
func (_mock *MockTrackerClient) UpdateTicket(ctx context.Context, ts string, id string, req trackerclient.UpdateTicketRequest) (trackerclient.Ticket, error) {
	ret := _mock.Called(ctx, ts, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTicket")
	}

	var r0 trackerclient.Ticket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, trackerclient.UpdateTicketRequest) (trackerclient.Ticket, error)); ok {
		return returnFunc(ctx, ts, id, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, trackerclient.UpdateTicketRequest) trackerclient.Ticket); ok {
		r0 = returnFunc(ctx, ts, id, req)
	} else {
		r0 = ret.Get(0).(trackerclient.Ticket)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, trackerclient.UpdateTicketRequest) error); ok {
		r1 = returnFunc(ctx, ts, id, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTrackerClient_UpdateTicket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTicket'
type MockTrackerClient_UpdateTicket_Call struct {
	*mock.Call
}

// UpdateTicket is a helper method to define mock.On call
//   - ctx context.Context
//   - ts string
//   - id string
//   - req trackerclient.UpdateTicketRequest
func (_e *MockTrackerClient_Expecter) UpdateTicket(ctx interface{}, ts interface{}, id interface{}, req interface{}) *MockTrackerClient_UpdateTicket_Call {
	return &MockTrackerClient_UpdateTicket_Call{Call: _e.mock.On("UpdateTicket", ctx, ts, id, req)}
}

func (_c *MockTrackerClient_UpdateTicket_Call) Run(run func(ctx context.Context, ts string, id string, req trackerclient.UpdateTicketRequest)) *MockTrackerClient_UpdateTicket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 trackerclient.UpdateTicketRequest
		if args[3] != nil {
			arg3 = args[3].(trackerclient.UpdateTicketRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTrackerClient_UpdateTicket_Call) Return(ticket trackerclient.Ticket, err error) *MockTrackerClient_UpdateTicket_Call {
	_c.Call.Return(ticket, err)
	return _c
}

func (_c *MockTrackerClient_UpdateTicket_Call) RunAndReturn(run func(ctx context.Context, ts string, id string, req trackerclient.UpdateTicketRequest) (trackerclient.Ticket, error)) *MockTrackerClient_UpdateTicket_Call {
	_c.Call.Return(run)
	return _c
}
